### ISSUE TITLE
Follow Forge 'Puppet Approved' Guidelines

### ISSUE THREAD

**Issue by MikaelSmith** [garethr/puppet-module-skeleton#81]
https://forge.puppetlabs.com/approved/criteria outlines Forge 'Puppet Approved' guidelines for puppet-lint, they're probably worth following.

**Comment by garethr** [comment]
At the moment the two lists mainly overlap, apart from the following extra rules in the skeleton.

* disable_documentation
* disable_single_quote_string_with_variables

I'm of a mind that classes should have documentation and that catching variables inside single quotes are both a good idea. My guess is the first is disabled because it would penalise the many many modules that don't bother documenting classes.
